#!/usr/bin/env php

<?php

use Rxak\Framework\App;
use Rxak\Framework\Console\Kernel;
use Rxak\Framework\Filesystem\Filesystem;

require __DIR__ . '/vendor/autoload.php';

App::init();

$kernel = new Kernel();

$kernel->run();
